version: "3.2"
networks:
    microservices:
      external: true
services:
  api:
    image: ${NEXT_APP_NAME}
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    container_name: ${NEXT_APP_NAME}
    restart: always
    env_file:
     - .env
    ports:
      - ${NEXT_APP_PORT}:${NEXT_APP_PORT}
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
