name: Build and Deploy to Cloud Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ production, sandbox ]
  
env:
  GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
  DEPLOY_REGION: us-central1 
  GCP_SA_KEY: ${{ secrets.GKE_SA_KEY }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get branch
      - name: Get branch
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      # Configure variables
      - name: Configure variables
        run: |
          echo "SERVICE_NAME=$(echo ${BRANCH_NAME}'-'${{ github.event.repository.name }})" >> $GITHUB_ENV
          echo "SECRET_CHUNK_NAME=$(echo 'ENVIRONMENT_'${BRANCH_NAME^^})" >> $GITHUB_ENV

      # Configure environment
      - name: Configure Environment
        id: package
        uses: ACE-Lan/sf-environments-action@main
        with:
          action: read
          chunk: ${{ secrets[env.SECRET_CHUNK_NAME] }}
          base: ${{ github.event.repository.name }}  

      # Setup gcloud
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
        
      - name: Build Docker image
        run: docker build . -t "gcr.io/$GCP_PROJECT_ID/$BRANCH_NAME/$SERVICE_NAME"
        
      - name: Push Docker image
        run: docker push "gcr.io/$GCP_PROJECT_ID/$BRANCH_NAME/$SERVICE_NAME"
        
      - name: Deploy Docker image
        run: gcloud run deploy $SERVICE_NAME --image "gcr.io/$GCP_PROJECT_ID/$BRANCH_NAME/$SERVICE_NAME" --allow-unauthenticated --region $DEPLOY_REGION